
labwiki:
  session:

    repositories:
      - name: plugin_ex
        type: file
        read_only: true
        top_dir: ../../plugins/labwiki_experiment_plugin/system_repo

    default_plugins: # Create these plugins the first time a user logs in
      - column: plan
        plugin: 'wiki'
        action: "on_get_content"
        url: 'plugin_ex:wiki/quickstart/quickstart.md'


  plugins:
    experiment:
      plugin_dir: labwiki_experiment_plugin
      job_service:
        host: localhost
        port: 8002

